<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>


    <ItemGroup> 
        <PackageReference Include="Azure.Messaging.ServiceBus" /> 
        <PackageReference Include="Polly"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
        <PackageReference Include="RabbitMQ.Client"/>

    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\Shared.Eventing\Shared.Eventing.csproj"/>
    </ItemGroup>
</Project>
