<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\SharedService\src\SharedService.Domain\SharedService.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shared.Domain"/>
        <Using Include="SharedService.Domain.ValueObjects"/>
    </ItemGroup> 
</Project>
