<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="MediatR"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Shared\Shared.Application\Shared.Application.csproj"/>
        <ProjectReference Include="..\..\..\..\Shared\Shared.Common\Shared.Common.csproj"/>
        <ProjectReference Include="..\..\..\SharedService\src\SharedService.Domain\SharedService.Domain.csproj"/>
        <ProjectReference Include="..\CatalogService.Application.Abstraction\CatalogService.Application.Abstraction.csproj"/>
        <ProjectReference Include="..\CatalogService.Domain\CatalogService.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shared.Application"/>
        <Using Include="Shared.Common"/>
        <Using Include="Shared.Application.Messaging"/>
        <Using Include="Shared.Application.Queries"/>
        <Using Include="CatalogService.Application.Abstraction"/>

        <Using Include="CatalogService.Application.Errors"/>
        <Using Include="SharedService.Domain.ValueObjects"/>
        <Using Include="CatalogService.Domain.Products.Aggregates"/>
        <Using Include="CatalogService.Domain.Products.Repository"/>
        <Using Include="CatalogService.Application.Abstraction.Products"/>
    </ItemGroup>

</Project>
