<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Shared\Shared.Domain\Shared.Domain.csproj" />
      <ProjectReference Include="..\..\..\CheckoutService\src\CheckoutService.Domain\CheckoutService.Domain.csproj" />
      <ProjectReference Include="..\..\..\SharedService\src\SharedService.Domain\SharedService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Products\Repository\" />
      <Folder Include="SharedValueObjects\" />
    </ItemGroup>
 
</Project>
