<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.AspNetCore.Routing"/>
        <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore"/>
        <PackageReference Include="Asp.Versioning.Mvc"/>
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer"/>
        <PackageReference Include="Swashbuckle.AspNetCore"/>
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations"/>
        <PackageReference Include="Scrutor"/>
        <PackageReference Include="Scalar.AspNetCore"/>

    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Services\CheckoutService\src\CheckoutService.DependencyInjection\CheckoutService.DependencyInjection.csproj"/>
        <ProjectReference Include="..\..\Services\InventoryService\src\InventoryService.DependencyInjection\InventoryService.DependencyInjection.csproj"/>
        <ProjectReference Include="..\..\Services\OrderService\src\OrderService.Application\OrderService.Application.csproj"/>
        <ProjectReference Include="..\..\Services\OrderService\src\OrderService.DependencyInjection\OrderService.DependencyInjection.csproj"/>
        <ProjectReference Include="..\..\Services\ProductService\src\CatalogService.Api\CatalogService.Api.csproj"/>
        <ProjectReference Include="..\..\Services\ProductService\src\CatalogService.DependencyInjection\CatalogService.DependencyInjection.csproj"/>
        <ProjectReference Include="..\..\Shared\Shared.Common\Shared.Common.csproj"/>
        <ProjectReference Include="..\..\Shared\Shared.Messaging\Shared.Messaging.csproj"/>
        <ProjectReference Include="..\..\Shared\Shared.Telemetry\Shared.Telemetry.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.AspNetCore.OpenApi"/>
        <Using Include="Microsoft.AspNetCore.Routing"/>
        <Using Include="Shared.Common"/>
        <Using Include="MediatR"/>
    </ItemGroup>


</Project>
