<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
 
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.EntityFrameworkCore"/>
        <Using Include="Microsoft.EntityFrameworkCore.Metadata.Builders"/>
    </ItemGroup>
 
    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Shared\Shared.Persistence\Shared.Persistence.csproj" />
        <ProjectReference Include="..\OrderService.Application\OrderService.Application.csproj"/>
    </ItemGroup>
 
    <ItemGroup>
        <Using Include="OrderService.Application.Abstraction"/>
    </ItemGroup>

</Project>
